default:
  module: "src.server.tasks.avalon.AvalonBench"
  parameters:
    concurrency: 5
    num_players: 5
    discussion: False

avalon-dev-naive:
  parameters:
    name: "AvalonBench-dev-naive"
    data_file: "data/avalon/dev.json"
    agent_list: ["naive", "naive", "naive", "naive", "naive"]

avalon-dev-single:
  parameters:
    name: "AvalonBench-dev-single"
    data_file: "data/avalon/dev.json"
    agent_list: ["search", "naive", "naive", "naive", "naive"]

avalon-dev-single-baseline:
  parameters:
    name: "AvalonBench-dev-single"
    data_file: "data/avalon/dev.json"
    agent_list: ["llm", "naive", "naive", "naive", "naive"]

avalon-dev-single-discuss-servant:
  parameters:
    name: "AvalonBench-dev-single"
    data_file: "data/avalon/dev_servant.json"
    agent_list: ["search", "speak_naive", "speak_naive", "speak_naive", "speak_naive"]
    discussion: True

avalon-dev-single-discuss:
  parameters:
    name: "AvalonBench-dev-discuss"
    data_file: "data/avalon/dev.json"
    agent_list: ["search", "speak_naive", "speak_naive", "speak_naive", "speak_naive"]
    discussion: True

avalon-dev-single-baseline-discuss:
  parameters:
    name: "AvalonBench-dev-discuss"
    data_file: "data/avalon/dev.json"
    agent_list: ["llm", "speak_naive", "speak_naive", "speak_naive", "speak_naive"]
    discussion: True

avalon-dev-single-search:
  parameters:
    name: "AvalonBench-dev-discuss"
    data_file: "data/avalon/dev.json"
    agent_list: ["search", "naive", "naive", "naive", "naive"]

avalon-dev-single-baseline:
  parameters:
    name: "AvalonBench-dev-discuss"
    data_file: "data/avalon/dev.json"
    agent_list: ["llm", "naive", "naive", "naive", "naive"]

avalon-dev-multi:
  parameters:
    name: "AvalonBench-dev-multi"
    data_file: "data/avalon/dev.json"
    agent_list: ["llm", "llm", "llm", "llm", "llm"]